[workspace]
resolver = "2"
members = ["proxelar-cli", "proxyapi", "proxyapi_models"]
default-members = ["proxelar-cli"]

[workspace.package]
rust-version = "1.97.1"

[workspace.dependencies.rama]
git = "https://github.com/plabayo/rama"
rev = "3490de1ff07d48432db25928fc8cf8bc3f5380b3"
default-features = false

[profile.release]
codegen-units = 1
lto = true
