[workspace]
resolver = "2"
members = ["proxelar-cli", "proxyapi", "proxyapi_models"]
default-members = ["proxelar-cli"]

[workspace.package]
rust-version = "1.97.1"

[workspace.dependencies.rama]
git = "https://github.com/plabayo/rama"
rev = "19eb9417bf36eba2a4176b83645d84c108c29e79"
default-features = false

[profile.release]
codegen-units = 1
lto = true
