[workspace]
resolver = "2"
members = ["proxelar-cli", "proxyapi", "proxyapi_models"]
default-members = ["proxelar-cli"]

[workspace.package]
rust-version = "1.97.1"

[workspace.dependencies.rama]
git = "https://github.com/plabayo/rama"
rev = "3ce00fb8e58e19ccd27e58f517d8e5858655f372"
default-features = false

[profile.release]
codegen-units = 1
lto = true
