name: Dependency check

on:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
  push:
    branches: ["master"]
    paths:
      - "**/Cargo.toml"
      - "Cargo.lock"
      - "deny.toml"
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
